// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package Domain

import (
	"task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewTaskUsecaseMock creates a new instance of TaskUsecaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecaseMock {
	mock := &TaskUsecaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskUsecaseMock is an autogenerated mock type for the TaskUsecase type
type TaskUsecaseMock struct {
	mock.Mock
}

type TaskUsecaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskUsecaseMock) EXPECT() *TaskUsecaseMock_Expecter {
	return &TaskUsecaseMock_Expecter{mock: &_m.Mock}
}

// AddNewTask provides a mock function for the type TaskUsecaseMock
func (_mock *TaskUsecaseMock) AddNewTask(task Domain.Task) (Domain.Task, error) {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for AddNewTask")
	}

	var r0 Domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Domain.Task) (Domain.Task, error)); ok {
		return returnFunc(task)
	}
	if returnFunc, ok := ret.Get(0).(func(Domain.Task) Domain.Task); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Get(0).(Domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(Domain.Task) error); ok {
		r1 = returnFunc(task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TaskUsecaseMock_AddNewTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewTask'
type TaskUsecaseMock_AddNewTask_Call struct {
	*mock.Call
}

// AddNewTask is a helper method to define mock.On call
//   - task Domain.Task
func (_e *TaskUsecaseMock_Expecter) AddNewTask(task interface{}) *TaskUsecaseMock_AddNewTask_Call {
	return &TaskUsecaseMock_AddNewTask_Call{Call: _e.mock.On("AddNewTask", task)}
}

func (_c *TaskUsecaseMock_AddNewTask_Call) Run(run func(task Domain.Task)) *TaskUsecaseMock_AddNewTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Domain.Task
		if args[0] != nil {
			arg0 = args[0].(Domain.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskUsecaseMock_AddNewTask_Call) Return(task1 Domain.Task, err error) *TaskUsecaseMock_AddNewTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *TaskUsecaseMock_AddNewTask_Call) RunAndReturn(run func(task Domain.Task) (Domain.Task, error)) *TaskUsecaseMock_AddNewTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTasks provides a mock function for the type TaskUsecaseMock
func (_mock *TaskUsecaseMock) GetAllTasks() []Domain.Task {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []Domain.Task
	if returnFunc, ok := ret.Get(0).(func() []Domain.Task); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Domain.Task)
		}
	}
	return r0
}

// TaskUsecaseMock_GetAllTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTasks'
type TaskUsecaseMock_GetAllTasks_Call struct {
	*mock.Call
}

// GetAllTasks is a helper method to define mock.On call
func (_e *TaskUsecaseMock_Expecter) GetAllTasks() *TaskUsecaseMock_GetAllTasks_Call {
	return &TaskUsecaseMock_GetAllTasks_Call{Call: _e.mock.On("GetAllTasks")}
}

func (_c *TaskUsecaseMock_GetAllTasks_Call) Run(run func()) *TaskUsecaseMock_GetAllTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TaskUsecaseMock_GetAllTasks_Call) Return(tasks []Domain.Task) *TaskUsecaseMock_GetAllTasks_Call {
	_c.Call.Return(tasks)
	return _c
}

func (_c *TaskUsecaseMock_GetAllTasks_Call) RunAndReturn(run func() []Domain.Task) *TaskUsecaseMock_GetAllTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function for the type TaskUsecaseMock
func (_mock *TaskUsecaseMock) GetTaskByID(id int) *Domain.Task {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *Domain.Task
	if returnFunc, ok := ret.Get(0).(func(int) *Domain.Task); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.Task)
		}
	}
	return r0
}

// TaskUsecaseMock_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type TaskUsecaseMock_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - id int
func (_e *TaskUsecaseMock_Expecter) GetTaskByID(id interface{}) *TaskUsecaseMock_GetTaskByID_Call {
	return &TaskUsecaseMock_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", id)}
}

func (_c *TaskUsecaseMock_GetTaskByID_Call) Run(run func(id int)) *TaskUsecaseMock_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskUsecaseMock_GetTaskByID_Call) Return(task *Domain.Task) *TaskUsecaseMock_GetTaskByID_Call {
	_c.Call.Return(task)
	return _c
}

func (_c *TaskUsecaseMock_GetTaskByID_Call) RunAndReturn(run func(id int) *Domain.Task) *TaskUsecaseMock_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTaskByID provides a mock function for the type TaskUsecaseMock
func (_mock *TaskUsecaseMock) RemoveTaskByID(id int) bool {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTaskByID")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// TaskUsecaseMock_RemoveTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTaskByID'
type TaskUsecaseMock_RemoveTaskByID_Call struct {
	*mock.Call
}

// RemoveTaskByID is a helper method to define mock.On call
//   - id int
func (_e *TaskUsecaseMock_Expecter) RemoveTaskByID(id interface{}) *TaskUsecaseMock_RemoveTaskByID_Call {
	return &TaskUsecaseMock_RemoveTaskByID_Call{Call: _e.mock.On("RemoveTaskByID", id)}
}

func (_c *TaskUsecaseMock_RemoveTaskByID_Call) Run(run func(id int)) *TaskUsecaseMock_RemoveTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TaskUsecaseMock_RemoveTaskByID_Call) Return(b bool) *TaskUsecaseMock_RemoveTaskByID_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *TaskUsecaseMock_RemoveTaskByID_Call) RunAndReturn(run func(id int) bool) *TaskUsecaseMock_RemoveTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTaskByID provides a mock function for the type TaskUsecaseMock
func (_mock *TaskUsecaseMock) UpdateTaskByID(id int, updatedTask Domain.Task) *Domain.Task {
	ret := _mock.Called(id, updatedTask)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskByID")
	}

	var r0 *Domain.Task
	if returnFunc, ok := ret.Get(0).(func(int, Domain.Task) *Domain.Task); ok {
		r0 = returnFunc(id, updatedTask)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.Task)
		}
	}
	return r0
}

// TaskUsecaseMock_UpdateTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTaskByID'
type TaskUsecaseMock_UpdateTaskByID_Call struct {
	*mock.Call
}

// UpdateTaskByID is a helper method to define mock.On call
//   - id int
//   - updatedTask Domain.Task
func (_e *TaskUsecaseMock_Expecter) UpdateTaskByID(id interface{}, updatedTask interface{}) *TaskUsecaseMock_UpdateTaskByID_Call {
	return &TaskUsecaseMock_UpdateTaskByID_Call{Call: _e.mock.On("UpdateTaskByID", id, updatedTask)}
}

func (_c *TaskUsecaseMock_UpdateTaskByID_Call) Run(run func(id int, updatedTask Domain.Task)) *TaskUsecaseMock_UpdateTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 Domain.Task
		if args[1] != nil {
			arg1 = args[1].(Domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskUsecaseMock_UpdateTaskByID_Call) Return(task *Domain.Task) *TaskUsecaseMock_UpdateTaskByID_Call {
	_c.Call.Return(task)
	return _c
}

func (_c *TaskUsecaseMock_UpdateTaskByID_Call) RunAndReturn(run func(id int, updatedTask Domain.Task) *Domain.Task) *TaskUsecaseMock_UpdateTaskByID_Call {
	_c.Call.Return(run)
	return _c
}
