// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package Domain

import (
	"task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewUserRepositoryMock creates a new instance of UserRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepositoryMock {
	mock := &UserRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepositoryMock is an autogenerated mock type for the UserRepository type
type UserRepositoryMock struct {
	mock.Mock
}

type UserRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepositoryMock) EXPECT() *UserRepositoryMock_Expecter {
	return &UserRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) Create(user *Domain.User) (*Domain.User, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Domain.User) (*Domain.User, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*Domain.User) *Domain.User); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Domain.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *Domain.User
func (_e *UserRepositoryMock_Expecter) Create(user interface{}) *UserRepositoryMock_Create_Call {
	return &UserRepositoryMock_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *UserRepositoryMock_Create_Call) Run(run func(user *Domain.User)) *UserRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Domain.User
		if args[0] != nil {
			arg0 = args[0].(*Domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_Create_Call) Return(user1 *Domain.User, err error) *UserRepositoryMock_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepositoryMock_Create_Call) RunAndReturn(run func(user *Domain.User) (*Domain.User, error)) *UserRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type UserRepositoryMock
func (_mock *UserRepositoryMock) GetByEmail(email string) (*Domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *Domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepositoryMock_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepositoryMock_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *UserRepositoryMock_Expecter) GetByEmail(email interface{}) *UserRepositoryMock_GetByEmail_Call {
	return &UserRepositoryMock_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *UserRepositoryMock_GetByEmail_Call) Run(run func(email string)) *UserRepositoryMock_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepositoryMock_GetByEmail_Call) Return(user *Domain.User, err error) *UserRepositoryMock_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepositoryMock_GetByEmail_Call) RunAndReturn(run func(email string) (*Domain.User, error)) *UserRepositoryMock_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}
