// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package Domain

import (
	"task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewUserUsecaseMock creates a new instance of UserUsecaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecaseMock {
	mock := &UserUsecaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserUsecaseMock is an autogenerated mock type for the UserUsecase type
type UserUsecaseMock struct {
	mock.Mock
}

type UserUsecaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUsecaseMock) EXPECT() *UserUsecaseMock_Expecter {
	return &UserUsecaseMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserUsecaseMock
func (_mock *UserUsecaseMock) Create(user *Domain.User) (*Domain.User, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *Domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Domain.User) (*Domain.User, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*Domain.User) *Domain.User); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Domain.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUsecaseMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserUsecaseMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *Domain.User
func (_e *UserUsecaseMock_Expecter) Create(user interface{}) *UserUsecaseMock_Create_Call {
	return &UserUsecaseMock_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *UserUsecaseMock_Create_Call) Run(run func(user *Domain.User)) *UserUsecaseMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Domain.User
		if args[0] != nil {
			arg0 = args[0].(*Domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserUsecaseMock_Create_Call) Return(user1 *Domain.User, err error) *UserUsecaseMock_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserUsecaseMock_Create_Call) RunAndReturn(run func(user *Domain.User) (*Domain.User, error)) *UserUsecaseMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type UserUsecaseMock
func (_mock *UserUsecaseMock) GetByEmail(email string) (*Domain.User, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *Domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Domain.User, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Domain.User); ok {
		r0 = returnFunc(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUsecaseMock_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserUsecaseMock_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *UserUsecaseMock_Expecter) GetByEmail(email interface{}) *UserUsecaseMock_GetByEmail_Call {
	return &UserUsecaseMock_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *UserUsecaseMock_GetByEmail_Call) Run(run func(email string)) *UserUsecaseMock_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserUsecaseMock_GetByEmail_Call) Return(user *Domain.User, err error) *UserUsecaseMock_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserUsecaseMock_GetByEmail_Call) RunAndReturn(run func(email string) (*Domain.User, error)) *UserUsecaseMock_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type UserUsecaseMock
func (_mock *UserUsecaseMock) Login(email string, password string) (string, error) {
	ret := _mock.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUsecaseMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UserUsecaseMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *UserUsecaseMock_Expecter) Login(email interface{}, password interface{}) *UserUsecaseMock_Login_Call {
	return &UserUsecaseMock_Login_Call{Call: _e.mock.On("Login", email, password)}
}

func (_c *UserUsecaseMock_Login_Call) Run(run func(email string, password string)) *UserUsecaseMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserUsecaseMock_Login_Call) Return(s string, err error) *UserUsecaseMock_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserUsecaseMock_Login_Call) RunAndReturn(run func(email string, password string) (string, error)) *UserUsecaseMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type UserUsecaseMock
func (_mock *UserUsecaseMock) Register(user *Domain.User) (*Domain.User, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *Domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Domain.User) (*Domain.User, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*Domain.User) *Domain.User); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Domain.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserUsecaseMock_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UserUsecaseMock_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - user *Domain.User
func (_e *UserUsecaseMock_Expecter) Register(user interface{}) *UserUsecaseMock_Register_Call {
	return &UserUsecaseMock_Register_Call{Call: _e.mock.On("Register", user)}
}

func (_c *UserUsecaseMock_Register_Call) Run(run func(user *Domain.User)) *UserUsecaseMock_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Domain.User
		if args[0] != nil {
			arg0 = args[0].(*Domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserUsecaseMock_Register_Call) Return(user1 *Domain.User, err error) *UserUsecaseMock_Register_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserUsecaseMock_Register_Call) RunAndReturn(run func(user *Domain.User) (*Domain.User, error)) *UserUsecaseMock_Register_Call {
	_c.Call.Return(run)
	return _c
}
